### ISSUE TITLE
Missing timezone in adsbexchange

### ISSUE THREAD

**Issue by Grandmasg** [mikenye/docker-readsb#18]
Saw an error in the log that the timezone was not set in section "Feeding adsbexchange.com"
Fixed with adding: - TZ=YOURTIMEZONE

**_Sample:_**
adsbx:
    image: mikenye/adsbexchange:latest
    tty: true
    container_name: adsbx
    restart: always
    environment:
      - BEASTHOST=readsb
      - LAT=YOURLATITUDE
      - LONG=YOURLONGITUDE
      - ALT=YOURALTITUDE
      - SITENAME=YOURSITENAME
      - UUID=YOURUUID
      **_- TZ=YOURTIMEZONE_**
    networks:
      - adsbnet

**Comment by mikenye** [comment]
Fixed, thanks for reporting this! :-)
