### ISSUE TITLE
Logrotate setup link broken

### ISSUE THREAD

**Issue by luciodaou** [mikenye/docker-readsb#30]
When clicking the link on Logging session "How-to-setup-log-rotation-post-installation", with the URL [https://success.docker.com/article/how-to-setup-log-rotation-post-installation](https://success.docker.com/article/how-to-setup-log-rotation-post-installation) I'm sent to Docker main webpage. Opening the link on any browser gives the same result.

Was the logrotate fixed on newer docker versions or do we still to configure it?

**Comment by mikenye** [comment]
Not sure why docker pulled that page. Odd.

I've documented the instructions here: <https://mikenye.gitbook.io/ads-b/setting-up-the-host-system/configure-docker> (the rest is a work in progress).
