### ISSUE TITLE
Add Github topics to the repository

### ISSUE THREAD

**Issue by mendel5** [mikenye/docker-readsb#33]
Hi, can you add the following topics to this repository?
* https://github.com/topics/readsb
* https://github.com/topics/adsb
* https://github.com/topics/mode-s
* https://github.com/topics/tis
* https://github.com/topics/sdr
* https://github.com/topics/rtlsdr
* https://github.com/topics/bladerf

Thanks!

**Comment by mikenye** [comment]
Done! Thanks for the suggestion.

**Comment by mendel5** [comment]
Sure!
